trigger:
- master

pool:
  name: Self Hosted

steps:
- script: echo Myfirst Azure Pipeline for maven project
  displayName: 'Run a one-line script'

- script: mvn clean install
  displayName: 'Build with maven'

- script: ls -l target/
  displayName: 'List target directory'

- script: java -jar target/MAVEN-1.0-SNAPSHOT.jar
  displayName: 'Run JAR'
